### ISSUE TITLE
Automatic switching between media resolutions

### ISSUE THREAD

**Issue by tracend** [addyosmani/video-player#5]
Common concerns delivering video is response time and bandwidth. 

Although you can use [media queries to deliver different source files](http://css-tricks.com/video-source-by-screen-size/) this is merely a one-sided approach to the _problem_. 

I'd like to ask if it is within scope for this tag to automatically switch resolutions based on cache, connection speed, memory, resolution...

**Comment by tracend** [comment]
After further consideration and following modular development principals (that web components are meant to enforce) I think it makes more sense for this functionality to be abstracted in its own tag. That way it could be used by other tags without the additional theming options. 

Work on this has started at: 
http://github.com/makesites/video-stream

**Comment by addyosmani** [comment]
I agree that it makes more sense for that functionality to be abstracted away. Will keep an eye on video-stream!

**Comment by tracend** [comment]
Thanks for the encouragement @addyosmani 

A first version is committed but there's definitely room for improvement. 

Feel free to send comments or participate in the development. 

I'll close this issue as I don't find it proper to remain open.
